# Site settings
title: Spring Mentor
email: springmentor@gmail.com
url: https://www.linkedin.com/in/mszarlinski
description: "Spring Framework Boot Cloud Netflix teaching learning mentor"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Spring Mentor

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/spring-petclinic/spring-petclinic-microservices
  - title: facebook
    url: https://www.facebook.com/Spring-Mentor-1930650606957081
  - title: linkedin
    url: https://www.linkedin.com/in/mszarlinski
  - title: twitter
    url: https://twitter.com/m_szarlinski

# Build settings
markdown: kramdown
permalink: pretty
